<?php
/**
 * Top menu for store
 *
 * @see Codevog_Navigation_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<!-- navigation BOF -->
<?php $_menu = $this->renderCategoriesMenuHtml(0, 'level-top', 'sub-wrapper' ) ?>
<?php if($_menu): ?>

    <ul  class="nav">
	    <?php if (Mage::getStoreConfig('templatesettings/templatesettings_header/navigation_home')): ?>
         <li class="level0 level-top">
         	<a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home'); ?></span></a>
         </li>
     <?php endif; ?>
        <?php
        echo $_menu;
        $custom_tab = Mage::getModel('cms/block')->load('template_navigation_block');
        if($custom_tab->getIsActive()) {
            echo '
            <li class="level0 level-top parent custom-block">
                <a href="#" class="level-top">
                    <span>'.$custom_tab->getTitle().'</span>
                </a>
                <div class="sub-wrapper">'.$this->getLayout()->createBlock('cms/block')->setBlockId('template_navigation_block')->toHtml().'</div>
            </li>';
        }
        ?>
        <li class="level0 level-top <?php if(strpos(Mage::helper('core/url')->getCurrentUrl(),Mage::getBaseUrl().'about_us') !== FALSE) echo ' active';?>">
            <a href="<?php echo Mage::getBaseUrl()?>about_us.html" class="level-top">
                <span><?php echo $this->__('Wir über Uns')?></span>
            </a>
        </li>
        <li class="level0 level-top <?php if(strpos(Mage::helper('core/url')->getCurrentUrl(),Mage::getBaseUrl().'wedding_cakes')!==FALSE) echo ' active';?>">
            <a href="<?php echo Mage::getBaseUrl()?>wedding_cakes.html" class="level-top">
                <span><?php echo $this->__('Hochzeitstorten')?></span>
            </a>
        </li>
        <li class="level0 level-top <?php if(strpos(Mage::helper('core/url')->getCurrentUrl(),Mage::getBaseUrl().'contacts')!==FALSE) echo ' active';?>">
            <a href="<?php echo Mage::getBaseUrl()?>contacts/" class="level-top">
                <span><?php echo $this->__('Kontakt')?></span>
            </a>
        </li>
    </ul>

<?php endif ?>
<!-- navigation EOF -->