

<?php  if($this->displayDeliveryDate()): ?>
<div class="col-set order-info-box">
    <div class="col">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Lieferung') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->__('Wunschtermin') ?>: <?php echo $this->getDisplayDeliveryDate(); ?><br/>
                <?php echo $this->__('Kundennachricht') ?>: <?php echo $this->getDisplayDeliveryComment(); ?><br/>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>