<div>
    <p>
        <strong style="color:#F00">
            <?php echo $this->__('Achten Sie bitte bei der Angabe Ihres Wunschtermins auf die angegebenen Lieferzeiten');?><br/>
            <?php echo $this->__('der einzelnen Produkte, sowie auf die Laufzeiten der von Ihnen gewählten Versandart.');?>
        </strong>
    </p>
    <div id="inputDateUser"></div>
    <div class="currentData"></div>
    <div><p style="font-size:14; color:#FF0000; font-weight:bold" >&nbsp;</p>
        <p style="font-size:14; color:#FF0000; font-weight:bold" ><?php echo $this->__('Um den Wunschtermin zu wählen, klicken Sie in das Datumsfeld!');?></p>
    </div>
    <div><br /><br /></div>
    <div class="required"><?php echo Mage::helper('codevog_delivery')->__("Wunschtermin:");?><em>*</em></div>
    <input type="hidden" class="inputDateUser">
    <input readonly="readonly" class="inputClass required-entry" type="text" value="<?php echo $this->get_minimal_date();?>" id="<?php echo $this->getFieldId('customer_notes')?>" name="<?php echo $this->getFieldName('customer_notes')?>" <?php echo $this->getFieldParams() ?>>
    <a href="#" onclick="if(jQuery('#DateUser').is(':hidden')) jQuery('#DateUser').show(); else jQuery('#DateUser').hide(); return false;">
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'codevog/delivery/cal-icon.png';?>" width="20px" height="20px" />
    </a>
    <div id="DateUser"></div>

    <?php $disable_dates = $this->get_disable_dates();?>

    <script type="text/javascript">

        jQuery.noConflict();

        var dataHoliday = [<?php echo $disable_dates;?>],
            $userThis = jQuery('#DateUser');

        //Init user DataPicker
        $userThis.DatePicker({
            mode: 'multiple',
            inline: true,
            date: dataHoliday,
            onBeforeShow: function(el){
            },
            onChange: function(date, el) {
                var monthZero = '';
                var dayZero = '';

                if(date[date.length-1].getMonth()+1 < 10)
                    monthZero = '0';
                if(date[date.length-1].getDate() < 10)
                    dayZero = '0';

                var dataCurrentCl =  dayZero + date[date.length-1].getDate() + "."  + monthZero +  (date[date.length-1].getMonth()+1) + '.' +  date[date.length-1].getFullYear();
                jQuery('.inputDateUser').val(dataCurrentCl);
                jQuery('.inputClass').val(dataCurrentCl);
                //jQuery('.datepickerSelected', el).addClass('datepickerHolydays');
                date.splice(date.length-1);


                //hide
                if(jQuery(el).is(":visible")) {
                    jQuery(el).hide();
                    jQuery('td', el).addClass('datepickerDisabled');
                    jQuery('td', el).removeClass('datepickerFuture');
                }


                //Click change
                jQuery('.inputClass, .change').bind('click', function(e){
                    $userThis.show();
                    jQuery(el).DatePickerSetDate(date);
                    //jQuery('.datepickerSelected', el).addClass('datepickerHolydays');
                    e.preventDefault();
                });
            }
        });

        $userThis.hide();

        jQuery('.inputClass, .change').bind('click', function(e){
            $userThis.show();
            e.preventDefault();
        });

        jQuery('.datepickerSelected').addClass('datepickerDisabled datepickerHolydays');

    </script>

</div>

<div class="form-list field">
    <label for="deliverydate"><?php echo $this->__('Kundennachricht:') ?></label>
    <div class="input-box">
        <textarea name="deliverycomment" id="deliverycomment" title="<?php echo $this->__('deliverycomment') ?>" class="input-text" ></textarea>
    </div>
</div>