<?php echo $this->getChildHtml('breadcrumbs') ?>
<div class="col-main">
    <?php echo $this->getChildHtml('global_messages') ?>
    <?php echo $this->getChildHtml('content') ?>
</div>
<div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>

<script type="text/javascript">

    var $ = jQuery.noConflict();
    $(document).ready(function()
    {
        $('select').selectik();
    });

</script>