<?php if(($categories = $this->getCategories()) && $categories->count()):?>

    <div class="category-products">

        <?php
            $columns = $this->getColumnCount();
            $columnCounter = 0;
        ?>

        <ul class="list-categories">
            <?php foreach($categories as $category):?>

                <?php $category = Mage::getModel('catalog/category')->load($category->getId());?>

                <?php ++$columnCounter;?>


                <li class="item <?php if($columnCounter == 1):?>first<?php elseif($columnCounter == $columns):?>last<?php endif;?>">
                    <a href="<?php echo $category->getUrl();?>" class="category-img">
                        <img alt="<?php echo $category->getName();?>" src="<?php echo $this->getCategoryImageUrl($category);?>">
                    </a>

                    <div class="info">
                        <h2 class="category-name">
                            <a title="<?php echo $category->getName();?>" href="<?php echo $category->getUrl();?>">
                                <?php echo $category->getName();?>
                            </a>
                        </h2>
                    </div>
                </li>
            <?php endforeach;?>
        </ul>

    </div>

<?php endif;?>